jobapp/jobapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("sitepages.urls",namespace="sitepages")),
    path("jobs/", include('jobs.urls')),
    path("accounts/", include('accounts.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

jobapp/jobs/urls.py
# In urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('create_job/', views.create_job, name='create_job'),
    path('job_post_success/', views.job_post_success, name='job_post_success'),
    path('manage/', views.manage_jobs, name='manage_jobs'),
    path('job/<int:pk>/update/',views.job_update, name='job_update'),
    path('job/<int:pk>/delete/',views.job_delete, name='job_delete'),
    path('success/', views.success_page, name='success_page'),
    path('apply/<int:job_id>/',views.apply_for_job, name='apply_for_job'),
    path('job/<int:job_id>/applicants/',views.view_applicants, name='view_applicants'),
    path('posted_jobs/', views.posted_jobs, name='posted_jobs'),
    path('save-job/<int:job_id>/', views.save_job, name='save_job'), 
    path('saved-jobs/', views.saved_jobs, name='saved_jobs'),
    path('saved-job-success/', views.save_job_success, name='save_job_success'),
    path('jobs/remove-saved/<int:job_id>/', views.remove_saved_job, name='remove_saved_job'),
    path('job-category/<str:category>/', views.job_category, name='job_category'),
    path('jobs-categorys/<str:category>/', views.jobs_category, name='jobs_categorys'),
    path('jobs-category/',views.Jobscategory,name="jobs-category"),
    path('search/', views.search_results, name='search_results'),
    path('search-results/', views.searchresults, name='searchs_results'),
    
    # path('apply/<int:job_id>/', views.apply_for_job, name='apply_for_job'),
    path('view-applied-jobs/', views.applied_jobs, name='view_applied_jobs'),
    path('view-job-listings/', views.Job_listings, name='view_Job_listings'),
    path('view-job-details/<int:job_id>/', views.Job_details, name='view_Job_details'),  

    # path('manage_jobs/', views.manage_jobs, name='manage_jobs'),
    # Add other URLs as needed
]

jobapp/sitepages/urls.py
from django.urls import path
from .views import *
app_name="sitepages"

urlpatterns = [
    path('',Home,name="homepage"),
    path('about/',About,name="about"),
    path('job-category/',Jobcategory,name="category"),
    path('job-listing/',Joblistings,name="listing"),
    path('job/<int:job_id>/', Jobdetails, name='job_details'),
    path('contact/',Contact,name="contact"),
    path('submit/', contact_submit, name='contact_submit'),
    path('message-success/<str:name>/', message_success, name='message_success'),
    path('testimonial/',Testimonial,name="testimonial"),
    path('register/',Register,name="register"),
]

jobapp/sitepages/models.py
from django.db import models



class ContactMessage(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject

jobapp/sitepages/views.py
from django.shortcuts import render,redirect,get_object_or_404
from jobs.models import Job
from jobs.forms import JobApplicationForm
from django.db.models import Count
from django.core.mail import send_mail
from django.conf import settings
from django.urls import reverse
from .models import ContactMessage

# Create your views here.
def Home(request):
    jobs = Job.objects.all()
    categories = dict(Job.CATEGORY_CHOICES)
    

    # Group jobs by job type
    job_types = Job.JOB_TYPE_CHOICES
    grouped_jobs = {}
    for job_type in job_types:
        grouped_jobs[job_type[0]] = jobs.filter(job_type=job_type[0])

   

    # Pass the list of jobs to the template context
    context = {
        'jobs': jobs,
        'grouped_jobs': grouped_jobs,
        'categories': categories,
        'ptitle': "Job Board - homepage"  # Add page title to the context
    } 

    return render(request, "sitepages/index.html", context)

def About(request):

    data = {"ptitle":"Job Board - About Us"}

    return render(request,"sitepages/about.html",data)


# views.py


def Jobcategory(request):
    categories = dict(Job.CATEGORY_CHOICES)
    context = {
        'categories': categories,
    }
    return render(request, 'sitepages/category.html', context)



def Joblistings(request):
    # Fetch the list of jobs from the database
    jobs = Job.objects.all()

    # Pass the list of jobs to the template context
    context = {
        'jobs': jobs,
        'ptitle': "Job Board - Listings"  # Add page title to the context
    } 

    return render(request, "sitepages/job-list.html", context)








def contact_submit(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')  # Retrieve the email entered by the user from the form
        subject = request.POST.get('subject')
        message = request.POST.get('message')

        # Save contact message to the database
        contact_message = ContactMessage.objects.create(
            name=name,
            email=email,
            subject=subject,
            message=message
        )

        # Send email using the email entered by the user as the sender
        send_mail(
            subject,
            f'Name: {name}\nEmail: {email}\nMessage: {message}',
            email,  # Use the email entered by the user as the sender
            [settings.EMAIL_HOST_USER],  # Your email address as the recipient
            fail_silently=False,
        )

        # Render the 'message_success' template directly
        return render(request, 'sitepages/message_success.html', {'ptitle': 'Job Board - Message success', 'name': name})

    else:
        return render(request, "sitepages/contact.html", {'ptitle': 'Job Board - Contact'})




def message_success(request, name):
    data = {
        "ptitle": "Job Board - Message success",
        "name": name
    }
    return render(request, 'sitepages/message_success.html', data)


def Contact(request):

    data = {"ptitle":"Job Board - Contact"}

    return render(request,"sitepages/contact.html",data)

def Testimonial(request):

    data = {"ptitle":"Job Board - Testimonials"}

    return render(request,"sitepages/testimonial.html",data)





def Jobdetails(request, job_id):
    # Retrieve the job object from the database based on job_id
    job = get_object_or_404(Job, pk=job_id)
    
    # Instantiate the job application form
    form = JobApplicationForm()
    
    # Pass the job object and form to the template
    data = {
        "ptitle": "Job Board - Job details",
        "job": job,
        "form": form  # Pass the form object to the template
    }

    return render(request, "sitepages/job-detail.html", data)



def Register(request):

    data = {"ptitle":"Job Board - register/signup"}

    return render(request,"sitepages/register.html",data)

jobapp/templates/sitepages/base1.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{{ptitle}}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap" rel="stylesheet">
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{%static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{%static 'lib/owlcarousel/assets/owl.carousel.min.css'%}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{%static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{%static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    <div class="container-xxl bg-white p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->


        <!-- Navbar Start -->
        <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
            <a href="/" class="navbar-brand d-flex align-items-center text-center py-0 px-4 px-lg-5">
                <h1 class="m-0 text-primary">JobEntry</h1>
            </a>
            <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav ms-auto p-4 p-lg-0">
                    <a href="/" class="nav-item nav-link active">Home</a>
                    <a href="{% url 'sitepages:about' %}" class="nav-item nav-link">About</a>
                    <!-- <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Jobs</a>
                        <div class="dropdown-menu rounded-0 m-0">
                            <a href="{% url 'sitepages:listing' %}" class="dropdown-item">Job List</a>
                        </div>
                    </div> -->
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                        <div class="dropdown-menu rounded-0 m-0">
                            <a href="{% url 'sitepages:category' %}" class="dropdown-item">Job Category</a>
                            <a href="{% url 'sitepages:testimonial' %}" class="dropdown-item">Testimonial</a>
                        </div>
                    </div>
                    <a href="{% url 'sitepages:contact' %}" class="nav-item nav-link">Contact</a>
                    {%if request.user.is_authenticated%}
                    <a href="{% url 'custom_logout' %}" class="nav-item nav-link">Logout</a>

                    {%else%}
                    <a href="{% url 'sitepages:register' %}" class="nav-item nav-link">Register</a>
                    <a href="{% url 'login' %}" class="nav-item nav-link">Login</a>
                    {%endif%}
                </div>
                <a href="{% url 'employer_signup' %}" class="btn btn-primary rounded-0 py-4 px-lg-5 d-none d-lg-block">Post A Job<i class="fa fa-arrow-right ms-3"></i></a>
            </div>
        </nav>
        <!-- Navbar End -->


        

        {%block homepage_content%}
        {%endblock%}

        {%block aboutpage_content%}
        {%endblock%}
        

        <!-- Footer Start -->
        <div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
            <div class="container py-5">
                <div class="row g-5">
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Quick Links</h5>
                        <a class="btn btn-link text-white-50" href="/">Home</a>
                        <a class="btn btn-link text-white-50" href="{% url 'sitepages:about' %}">About Us</a>
                        <a class="btn btn-link text-white-50" href="{% url 'sitepages:category' %}">Job Category</a>
                        <a class="btn btn-link text-white-50" href="{% url 'sitepages:testimonial' %}">Testimonial</a>
                        <a class="btn btn-link text-white-50" href="{% url 'sitepages:contact' %}">Contact</a>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Contact</h5>
                        <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                        <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                        <p class="mb-2"><i class="fa fa-envelope me-3"></i>Oluwajimi@gmail.com</p>
                        <div class="d-flex pt-2">
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Newsletter</h5>
                        <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                        <div class="position-relative mx-auto" style="max-width: 400px;">
                            <input class="form-control bg-transparent w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                            <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="copyright">
                    <div class="row">
                        <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                            &copy; <a class="border-bottom" href="#">Oluwajimi</a>, All Right Reserved. 
							
							<!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
							Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>
                        </div>
                        <div class="col-md-6 text-center text-md-end">
                            <div class="footer-menu">
                                <a href="">Home</a>
                                <a href="">Cookies</a>
                                <a href="">Help</a>
                                <a href="">FQAs</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{%static 'lib/wow/wow.min.js' %}"></script>
    <script src="{%static 'lib/easing/easing.min.js' %}"></script>
    <script src="{%static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{%static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{%static 'js/main.js' %}"></script>
</body>

</html>

jobapp/templates/sitepages/base2.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{{ptitle}}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap" rel="stylesheet">
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{%static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{%static 'lib/owlcarousel/assets/owl.carousel.min.css'%}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{%static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{%static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    <div class="container-xxl bg-white p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->


        <!-- Navbar Start -->
        <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
            <a href="{% url 'employer_dashboard' %}" class="navbar-brand d-flex align-items-center text-center py-0 px-4 px-lg-5">
                <h1 class="m-0 text-primary">JobEntry</h1>
            </a>
            <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav ms-auto p-4 p-lg-0">
                    <a href="{% url 'manage_jobs' %}" class="nav-item nav-link">Manage Jobs</a>
                    <a href="{% url 'posted_jobs' %}" class="nav-item nav-link">View Posted Jobs</a>
                    <a href="{% url 'edit_employer_profile' %}" class="nav-item nav-link">Profile settings</a>
                    {%if request.user.is_authenticated%}
                    <a href="{% url 'custom_logout' %}" class="nav-item nav-link">Logout</a>

                    {%else%}
                    <a href="{% url 'sitepages:register' %}" class="nav-item nav-link">Register</a>
                    <a href="{% url 'login' %}" class="nav-item nav-link">Login</a>
                    {%endif%}
                </div>
                <a href="{% url 'create_job' %}" class="btn btn-primary rounded-0 py-4 px-lg-5 d-none d-lg-block">Post A Job<i class="fa fa-arrow-right ms-3"></i></a>
            </div>
        </nav>
        <!-- Navbar End -->


        

        {%block homepage_content%}
        {%endblock%}

        {%block aboutpage_content%}
        {%endblock%}
        

        <!-- Footer Start -->
        <div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
            <div class="container py-5">
                <div class="row g-5">
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Quick Links</h5>
                        <a class="btn btn-link text-white-50" href="{% url 'manage_jobs' %}">Manage Jobs</a>
                        <a class="btn btn-link text-white-50" href="{% url 'posted_jobs' %}">View Posted Jobs</a>
                        <a class="btn btn-link text-white-50" href="{% url 'edit_employer_profile' %}">Profile settings</a> 
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Contact</h5>
                        <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                        <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                        <p class="mb-2"><i class="fa fa-envelope me-3"></i>Oluwajimi@gmail.com</p>
                        <div class="d-flex pt-2">
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Newsletter</h5>
                        <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                        <div class="position-relative mx-auto" style="max-width: 400px;">
                            <input class="form-control bg-transparent w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                            <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="copyright">
                    <div class="row">
                        <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                            &copy; <a class="border-bottom" href="#">Oluwajimi</a>, All Right Reserved. 
							
							<!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
							Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>
                        </div>
                        <div class="col-md-6 text-center text-md-end">
                            <div class="footer-menu">
                                <a href="">Home</a>
                                <a href="">Cookies</a>
                                <a href="">Help</a>
                                <a href="">FQAs</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{%static 'lib/wow/wow.min.js' %}"></script>
    <script src="{%static 'lib/easing/easing.min.js' %}"></script>
    <script src="{%static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{%static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{%static 'js/main.js' %}"></script>
</body>

</html>

jobapp/templates/sitepages/category.html
{%extends 'sitepages/base1.html'%}
{%load static%}
{%block aboutpage_content%}

        <!-- Header End -->
        <div class="container-xxl py-5 bg-dark page-header mb-5">
            <div class="container my-5 pt-5 pb-4">
                <h1 class="display-3 text-white mb-3 animated slideInDown">{{ptitle}}</h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb text-uppercase">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item"><a href="#">Pages</a></li>
                        <li class="breadcrumb-item text-white active" aria-current="page">Category</li>
                    </ol>
                </nav>
            </div>
        </div>
        <!-- Header End -->

<!-- category.html -->

{% load job_count %}

<div class="container-xxl py-5">
    <div class="container">
        <h1 class="text-center mb-5 wow fadeInUp" data-wow-delay="0.1s">Explore By Category</h1>
        <div class="row g-4">
            {% for category, display_name in categories.items %}
            <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.{{ forloop.counter }}s">
                <div class="cat-item rounded p-4">
                    <a href="{% url 'job_category' category=category %}">
                        <h6 class="mb-3">{{ display_name }}</h6>
                        <p class="mb-0">{{ category|job_count }} Job{% if category|job_count != 1 %}s{% endif %}</p>
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>



<!-- Category End -->






       {%endblock%}

jobapp/templates/sitepages/job-list.html
{% extends 'sitepages/base1.html' %}
{% load static%}
{% block homepage_content %}


        <!-- Header End -->
        <div class="container-xxl py-5 bg-dark page-header mb-5">
            <div class="container my-5 pt-5 pb-4">
                <h1 class="display-3 text-white mb-3 animated slideInDown">{{ptitle}}</h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb text-uppercase">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item"><a href="#">Pages</a></li>
                        <li class="breadcrumb-item text-white active" aria-current="page">Job List</li>
                    </ol>
                </nav>
            </div>
        </div>
        <!-- Header End -->


        <!-- Jobs Start -->
        <div class="container-xxl py-5">
            <div class="container">
                <h1 class="text-center mb-5 wow fadeInUp" data-wow-delay="0.1s">Job Listing</h1>
                <div class="tab-class text-center wow fadeInUp" data-wow-delay="0.3s">
                    <ul class="nav nav-pills d-inline-flex justify-content-center border-bottom mb-5">
                        <li class="nav-item">
                            <a class="d-flex align-items-center text-start mx-3 ms-0 pb-3 active" data-bs-toggle="pill" href="#tab-1">
                                <h6 class="mt-n1 mb-0">Featured</h6>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="d-flex align-items-center text-start mx-3 pb-3" data-bs-toggle="pill" href="#tab-2">
                                <h6 class="mt-n1 mb-0">Full Time</h6>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="d-flex align-items-center text-start mx-3 me-0 pb-3" data-bs-toggle="pill" href="#tab-3">
                                <h6 class="mt-n1 mb-0">Part Time</h6>
                            </a>
                        </li>
                    </ul>
                    <div class="tab-content">
            <div id="tab-1" class="tab-pane fade show p-0 active">
            {% for job in jobs %}
            <div class="job-item p-4 mb-4">
                <div class="row g-4">
                    <div class="col-sm-12 col-md-8 d-flex align-items-center">
                        <img class="flex-shrink-0 img-fluid border rounded" src="{{ job.company_logo.url }}" alt="{{ job.company_logo }}" style="width: 80px; height: 80px;">
                        <div class="text-start ps-4">
                            <h5 class="mb-3">{{ job.job_title }}</h5>
                            <span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>{{ job.location }}</span>
                            <span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>{{ job.job_type }}</span>
                            <span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>{{ job.salary_range }}</span>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">
                        <div class="d-flex mb-3">
                            <a class="btn btn-light btn-square me-3" href=""><i class="far fa-heart text-primary"></i></a>
                            <a class="btn btn-primary" href="{% url 'sitepages:job_details' job_id=job.id %}">Apply Now</a>
                        </div>
                        <small class="text-truncate"><i class="far fa-calendar-alt text-primary me-2"></i>DeadLine: {{ job.application_deadline }}</small>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <a class="btn btn-primary py-3 px-5" href="">Browse More Jobs</a>
    </div>
</div>
                            
        </div>
        <!-- Jobs End -->
{%endblock%}

        